apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - service-accounts.yaml
  - postgres-core.yaml
  - postgres-keycloak.yaml
  - redis-bff.yaml
  - redis-core.yaml
  - keycloak.yaml
  - core.yaml
  - bff.yaml
  - hpa.yaml
  - routes.yaml
  - market-order-edge.yaml
