apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bff
  namespace: hero-association
spec:
  parentRefs:
    - name: hero-association
      sectionName: https
  hostnames:
    - k3d.heroassociation.test
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /auth
        - path:
            type: PathPrefix
            value: /ws
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: X-Forwarded-Host
                value: k3d.heroassociation.test
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Port
                value: "443"
      backendRefs:
        - name: bff
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: hero-association
spec:
  parentRefs:
    - name: hero-association
      sectionName: https
  hostnames:
    - auth.k3d.heroassociation.test
  rules:
    - backendRefs:
        - name: keycloak
          port: 8080
