apiVersion: v1
kind: ServiceAccount
metadata:
  name: hero-association-bff
  namespace: hero-association
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hero-association-core
  namespace: hero-association

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hero-association-market
  namespace: hero-association

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hero-association-assets
  namespace: hero-association
