FROM maven:3.9.16-eclipse-temurin-25 AS maven

FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 AS build

COPY --from=maven --chown=1001:1001 /usr/share/maven /opt/maven

ENV MAVEN_HOME=/opt/maven
ENV PATH=/opt/maven/bin:${PATH}

WORKDIR /project

COPY --chown=1001:1001 pom.xml .
RUN mvn --batch-mode dependency:go-offline

COPY --chown=1001:1001 src src
RUN mvn --batch-mode package -Dnative -DskipTests -Denforcer.skip=true

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

WORKDIR /work

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --from=build --chown=1001:root --chmod=755 /project/target/*-runner /work/application

EXPOSE 8080

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
