apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    logging:
      level:
        default: info
    provider:
      type: Kubernetes
      kubernetes:
        rateLimitDeployment:
          container:
            image: docker.io/envoyproxy/ratelimit:8fe6ea42
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                      - name: envoy-ratelimit
                        imagePullPolicy: IfNotPresent
                        env:
                          - name: REDIS_HEALTH_CHECK_ACTIVE_CONNECTION
                            value: "true"
                          - name: REDIS_TYPE
                            value: sentinel
        shutdownManager:
          image: envoyproxy/gateway:v1.9.1
    rateLimit:
      failClosed: true
      timeout: 200ms
      backend:
        type: Redis
        redis:
          url: gateway,redis-gateway-ha-0.redis-gateway-ha.envoy-gateway-system.svc.cluster.local:26379,redis-gateway-ha-1.redis-gateway-ha.envoy-gateway-system.svc.cluster.local:26379,redis-gateway-ha-2.redis-gateway-ha.envoy-gateway-system.svc.cluster.local:26379
