FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 AS native-build

WORKDIR /workspace

COPY --chown=quarkus:quarkus mvnw ./mvnw
COPY --chown=quarkus:quarkus .mvn .mvn
COPY --chown=quarkus:quarkus pom.xml ./
COPY --chown=quarkus:quarkus hero-association-bff/pom.xml ./hero-association-bff/pom.xml
COPY --chown=quarkus:quarkus hero-association-expedition/pom.xml ./hero-association-expedition/pom.xml
COPY --chown=quarkus:quarkus hero-association-market/pom.xml ./hero-association-market/pom.xml
COPY --chown=quarkus:quarkus hero-association-assets/pom.xml ./hero-association-assets/pom.xml
COPY --chown=quarkus:quarkus hero-association-lib ./hero-association-lib
COPY --chown=quarkus:quarkus hero-association-core/pom.xml ./hero-association-core/pom.xml
COPY --chown=quarkus:quarkus hero-association-core/src ./hero-association-core/src

USER quarkus

RUN ./mvnw --batch-mode -pl hero-association-core -am package -Dnative -DskipTests

FROM scratch AS native-artifact

COPY hero-association-core/target/*-runner /application

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0 AS native-runtime-base

WORKDIR /work

EXPOSE 8081

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]

FROM native-runtime-base AS native-runtime

COPY --from=native-artifact --chown=1001:root --chmod=0755 /application /work/application

FROM native-runtime-base AS native-multistage

COPY --from=native-build --chown=1001:root --chmod=0755 /workspace/hero-association-core/target/*-runner /work/application
