FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 AS native-build

WORKDIR /workspace

COPY --chown=quarkus:quarkus mvnw ./mvnw
COPY --chown=quarkus:quarkus .mvn .mvn
COPY --chown=quarkus:quarkus pom.xml ./

USER quarkus

RUN ./mvnw --batch-mode dependency:go-offline

COPY --chown=quarkus:quarkus src ./src

RUN ./mvnw --batch-mode package -Dnative -DskipTests

FROM scratch AS native-artifact

COPY target/*-runner /application

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0 AS native-runtime-base

WORKDIR /work

EXPOSE 8080

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]

FROM native-runtime-base AS native-runtime

COPY --from=native-artifact --chown=1001:root --chmod=0755 /application /work/application

FROM native-runtime-base AS native-multistage

COPY --from=native-build --chown=1001:root --chmod=0755 /workspace/target/*-runner /work/application
