<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.tiagovibeson</groupId>
    <artifactId>hero-association-backend</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>hero-association-lib</module>
        <module>hero-association-assets</module>
        <module>hero-association-core</module>
        <module>hero-association-expedition</module>
        <module>hero-association-market</module>
        <module>hero-association-bff</module>
    </modules>
</project>
