quarkus.application.name=hero-association
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.image-name=postgres:18.6-alpine3.24
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hero_association
%dev.quarkus.datasource.username=hero_association
%dev.quarkus.datasource.password=hero_association
%dev.quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
%test.quarkus.scheduler.enabled=false
