apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
  namespace: hero-association
spec:
  replicas: 2
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: assets
          env:
            - name: HERO_ASSOCIATION_OIDC_ISSUER
              value: https://auth.e2e.heroassociation.test/realms/hero-association
