apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: hero-association
spec:
  template:
    spec:
      containers:
        - name: keycloak
          env:
            - name: KC_HOSTNAME
              value: https://auth.e2e.heroassociation.test
