apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hero-association-e2e
resources:
  - ../backend
  - ../frontend
  - ../expedition
patches:
  - path: namespace-patch.yaml
  - path: bff-patch.yaml
  - path: core-patch.yaml
  - path: keycloak-patch.yaml
  - path: expedition-patch.yaml
  - path: delete-hpa.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: bff
    path: app-route-patch.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: frontend
    path: app-route-patch.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: market-order-placement
    path: app-route-patch.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: keycloak
    path: auth-route-patch.yaml
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: bff
    path: bff-forwarded-host-patch.yaml
