apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hero-association-components
resources:
  - ../backend/postgres-core.yaml
  - ../backend/redis-core.yaml
  - ../backend/redis-bff.yaml
  - ../expedition/rabbitmq.yaml
  - ../expedition/redis.yaml
